[build]
  command="ng build"
  publish="dist/angular-quickstart"


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
[[redirects]]
  from = "/assets/img"
  to = "/img"
  status = 200
  force = true
  query = {path = ":path"}

[[plugins]]
  package = "netlify-plugin-cypress"

  [plugins.inputs.postBuild]
    enable = true

  [plugins.inputs]
    enable = false
