[build]
  command="ng build"
  publish="dist/angular-quickstart"

[[redirects]]
  from = "/app-ads.txt"
  to = "/assets/app-ads.txt"
  status = 200
  force = true

[[redirects]]
  from = "app-ads.txt"
  to = "assets/app-ads.txt"
  status = 200
  force = true

[[redirects]]
  from = "/img"
  to = "/assets/img"
  status = 200
  force = true

[[redirects]]
  from = "img"
  to = "assets/img"
  status = 200
  force = true

[[plugins]]
  package = "netlify-plugin-cypress"

  [plugins.inputs.postBuild]
    enable = true

  [plugins.inputs]
    enable = false
