[build]
  command="ng build"
  publish="dist/angular-quickstart"
  
# publish = "img/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "netlify-plugin-cypress"

  [plugins.inputs.postBuild]
    enable = true

  [plugins.inputs]
    enable = false

#[build.processing]
#  skip_processing = false
#[build.processing.images]
#  compress = true
